sudo: false

language: scala
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.m2

jdk:
- openjdk8

matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
      jdk: openjdk8
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.8
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.8
      env: PLAY_VERSION=2.7
      jdk: openjdk8
